// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class objetoremoto_Stub
    extends java.rmi.server.RemoteStub
    implements iobjetoremoto, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_Saludo_0;
    
    static {
	try {
	    $method_Saludo_0 = iobjetoremoto.class.getMethod("Saludo", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public objetoremoto_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of Saludo(String)
    public void Saludo(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_Saludo_0, new java.lang.Object[] {$param_String_1}, -8038431060176985722L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
